project:
  type: book

book:
  title: "Advanced Statistics 25/26"
  author: "Martina Sladekova"
  date: "12/30/2025"
  chapters:
    - index.qmd
    - part: 01_gzlms.qmd
      chapters: 
       - 01a_gzlms_skewed.qmd
       - 01b_gzlms_counts.qmd
       - 01c_gzlms_ordinal.qmd
       - 01d_gzlms_summary.qmd
    - part: 02_ma.qmd
      chapters: 
       - 02a_ma_intro.qmd 
       - 02b_ma_advanced.qmd
       - 02c_ma_assessment_support.qmd  
    - part: 03_measurement.qmd
      chapters: 
       - 03a_measurement_1.qmd 
       - 03b_measurement_2.qmd  
       - 03c_measurement_3.qmd
    - 04_cex.qmd  
    - 05_open_topic.qmd   
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    highlight-style: tango
    toc-depth: 4
    toc-expand: 4
    number-depth: 2
  # pdf:
  #   documentclass: scrreprt
